- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/utils.py
In production the expected behavior is to call the Superset API via HTTPS, however for local development we can't use the superset host to connect to the API due that `local.edly.io` points to `127.0.0.1` which in a container is in the container port, not the local machine.
This PR fixed the development server by preferring using the `internal_service_url` (`superset:8088`) over the `service_url`. In production, this variable is not included so that it defaults to the `service_url`.
A proper PR in tutor-contrib-aspects is created to align with the changes: https://github.com/openedx/tutor-contrib-aspects/pull/656
Working locally and remote:
> fix: use internal_service_url over service_url

- platform_plugin_aspects/static/html/superset.html
- platform_plugin_aspects/tests/test_xblock.py
- platform_plugin_aspects/xblock.py
Initial XBlock display (without editing configuration) shows a confusing error:
This change fixes this by checking to see if the `dashboard_uuid` is set before using it as the `superset_dashboards` context:
And now after editing the XBlock to set `dashboard_uuid = 1d6bf904-f53f-47fd-b1c9-6cd7e284d286` (and refresh..):
> fix: xblock not rendering correctly when no dashboard_uuid is set

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/extensions/filters.py
- platform_plugin_aspects/settings/common.py
- platform_plugin_aspects/settings/production.py
- platform_plugin_aspects/settings/tests/test_settings.py
- platform_plugin_aspects/static/css/superset.css
- platform_plugin_aspects/static/html/superset.html
- platform_plugin_aspects/static/js/embed_dashboard.js
- platform_plugin_aspects/templates/instructor_dashboard/aspects.html
- platform_plugin_aspects/tests/test_utils.py
- platform_plugin_aspects/tests/test_xblock.py
- platform_plugin_aspects/utils.py
- platform_plugin_aspects/xblock.py
- test_settings.py
This PR allows embedding multiple superset dashboards in the LMS instructor dashboard.
Tested against: https://github.com/openedx/tutor-contrib-aspects/pull/666
> feat: allow embedding multiple superset dashboards

- CHANGELOG.rst
- docs/how-tos/index.rst
- docs/how-tos/load_test_tracking_pipeline.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/management/commands/load_test_tracking_events.py
- platform_plugin_aspects/management/commands/monitor_load_test_tracking.py
- platform_plugin_aspects/tests/commands/test_load_test_monitor.py
- platform_plugin_aspects/tests/commands/test_load_test_tracking_events.py
- platform_plugin_aspects/utils.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
- test_settings.py
- tox.ini
This is a fully functional version of a load test script that works in dev and local environments. K8s not yet tested, directions are provided in the docs.
> feat: Add commands to load test tracking event pipelines

- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
Using django-rest-framework causes spurious Dependabot alerts. It's just an alias for djangorestframework so we should be using that instead.
> chore: Use correct name for drf dependency

- README.rst
- docs/how-tos/load_test_tracking_pipeline.rst
> chore: update readme with settings

- Makefile
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.txt
A variety of errors happen in openedx-translations when trying to use i18n_tools to extract. Since we don't seem to need any of that functionality, we can just use the django commands. This was successfully tested in my fork.
> build: Fix extract_translations when run in openedx-translations

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/apps.py
- platform_plugin_aspects/extensions/filters.py
- platform_plugin_aspects/extensions/tests/test_filters.py
- platform_plugin_aspects/signals.py
- platform_plugin_aspects/static/html/superset.html
- platform_plugin_aspects/static/js/embed_dashboard.js
- platform_plugin_aspects/static/js/superset.js
- platform_plugin_aspects/tests/test_utils.py
- platform_plugin_aspects/tests/test_views.py
- platform_plugin_aspects/tests/test_xblock.py
- platform_plugin_aspects/urls.py
- platform_plugin_aspects/utils.py
- platform_plugin_aspects/views.py
- platform_plugin_aspects/xblock.py
- requirements/test.in
- test_settings.py
Closes https://github.com/openedx/platform-plugin-aspects/issues/23
**Testing instructions**
1. Load the Instructor Dashboard
1. Ensure you can continue to use Superset uninterrupted for 5 min.
1. Add the SupersetXBlock to a course
1. Ensure you can continue to use Superset within the XBlock in the LMS and Studio for 5 min.
> feat: adds endpoints for fetchGuestToken

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/extensions/filters.py
- platform_plugin_aspects/extensions/tests/test_filters.py
- platform_plugin_aspects/static/html/superset.html
- platform_plugin_aspects/tests/test_utils.py
- platform_plugin_aspects/utils.py
- test_settings.py
After these changes embedded dashboards should load again. It is currently expected that there will be dataset errors showing up and some data may not appear, that's being worked on elsewhere.
> fix: Fix slug repeating language and change tab name

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/extensions/filters.py
- platform_plugin_aspects/settings/common.py
- platform_plugin_aspects/utils.py
This fixes mismatches between this plugin and the assets generated in Aspects that cause translated dashboards to not embed properly. There is a matching PR in tutor-contrib-aspects that is needed to complete this fix.
> fix: Normalize localized asset UUIDs

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/static/html/superset.html
- platform_plugin_aspects/static/js/embed_dashboard.js
- platform_plugin_aspects/static/js/superset.js
- platform_plugin_aspects/tests/test_utils.py
- platform_plugin_aspects/tests/test_views.py
- platform_plugin_aspects/utils.py
- platform_plugin_aspects/views.py
- platform_plugin_aspects/xblock.py
This PR fixes the Superset XBlock:
- Current course filters are applied.
- The filter now only filters by `org` and `course_key`.
> fix: allow to embed dashboards in xblock

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/conf/locale/en/LC_MESSAGES/django.po
- platform_plugin_aspects/settings/common.py
- platform_plugin_aspects/static/html/superset.html
> refactor: Allow configured dashboard tabs to be translated

- platform_plugin_aspects/settings/common.py
The dashboard name changed, so did the slug. Technically this slug isn't used from this location as the config is overwritten in tutor-contrib-aspects, but I just want to keep them in sync.
> refactor: Update course dashboard slug to match tutor plugin

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/xblock.py
> fix: Fix xblock.utils imports for pre-quince releases

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/views.py
This may be temporary and require further caching, but right now I think it may be a premature optimization and is causing a variety of bugs.
Closes: https://github.com/openedx/tutor-contrib-aspects/issues/759
> fix: Turn off superset guest token caching

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/extensions/filters.py
- platform_plugin_aspects/management/commands/load_test_tracking_events.py
- platform_plugin_aspects/management/commands/monitor_load_test_tracking.py
- platform_plugin_aspects/sinks/serializers.py
- platform_plugin_aspects/sinks/tests/test_serializers.py
- platform_plugin_aspects/tests/test_xblock.py
This PR fixes an issue when serializing as JSON the course data where some attributes were dates cannot be encoded by default. We use the code from `event-tracking` to allow the serialization of datetime objects as JSON.
> fix: serialize datetime objects as strings

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/signals.py
- platform_plugin_aspects/xblock.py
Sometimes the user profile sink would get run before the transaction creating the target row was committed in the LMS. This led to UserProfileNotFound errors and the data not making its way to ClickHouse. This delays creating the task until the transaction is committed.
Closes: #54 
> fix: User profile not found on account creation

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/sinks/course_overview_sink.py
- platform_plugin_aspects/sinks/tests/test_course_overview_sink.py
- platform_plugin_aspects/tests/test_utils.py
- test_utils/helpers.py
We've been using Modulestore's get_items, but even though it's often correct the ordering isn't guaranteed. The new method walks the course tree itself, then adds in the detached models separately.
Potential concerns:
This was already a pretty heavy operation, calling into Modulestore twice to walk all of the blocks may not be performant enough or cause issues in the LMS/CMS. It may be preferable to ignore detached blocks if we are not currently using them, but I wanted to preserve parity with what we've been doing unless/until there is an actual problem.
Closes: #61 
> fix: Fix course-overviews sink not ordering blocks correctly

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/sinks/course_overview_sink.py
- test_utils/helpers.py
The last change caused the "order" key to move to a new place in the CSV, breaking import ordering. This fixes that and adds a test for the order key.
> Fix course block CSV ordering

- CHANGELOG.rst
- README.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/apps.py
- platform_plugin_aspects/settings/common.py
- platform_plugin_aspects/signals.py
- platform_plugin_aspects/sinks/__init__.py
- platform_plugin_aspects/sinks/base_sink.py
- platform_plugin_aspects/sinks/course_enrollment_sink.py
- platform_plugin_aspects/sinks/serializers.py
- platform_plugin_aspects/sinks/tests/test_course_enrollment_sink.py
This PR creates a sink for the Course Enrollment mode. It uses the `ENROLL_STATUS_CHANGE` signal to listen for changes in enrollments.
1. Check out this branch on your local repository.
2. Run Aspects migrations to create the necessary table.
3. Enable the course enrollment sink waffle flag `event_sink_clickhouse.course_enrollment.enabled`.
4. Enroll/unenroll in a course via the courseware page or in the instructor dashboard.
5. Verify a record is stored for the enrollment.
6. Verify the `dump_data_to_clickhouse` can dump old data.
> feat: add course enrollment sink

- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
See: https://github.com/openedx/wg-build-test-release/issues/383
> chore: update Django to 4.2.14 for Redwood - Security Patch

- .github/workflows/ci.yml
- tox.ini
From 3.8 and 3.11.
edx-platform has moved to 3.11, we no longer need to support 3.8 and some requirements we have are starting to require 3.9+. See: https://github.com/openedx/platform-plugin-aspects/pull/71
> chore: Change tested Python version to 3.11 & 3.12

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/settings/common.py
- platform_plugin_aspects/signals.py
- platform_plugin_aspects/sinks/__init__.py
- platform_plugin_aspects/sinks/serializers.py
- platform_plugin_aspects/sinks/tag_sink.py
- platform_plugin_aspects/tasks.py
- platform_plugin_aspects/tests/test_utils.py
- platform_plugin_aspects/utils.py
This PR adds two new sinks for the Tag and Taxonomy models in `openedx-learning`.
Closes: https://github.com/openedx/tutor-contrib-aspects/issues/926 
> feat: add tag and taxonomy sink

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/static/js/embed_dashboard.js
- platform_plugin_aspects/static/js/superset.js
This PR delays the loading of unfocused dashboards.
https://github.com/user-attachments/assets/0080ab4b-abba-4565-b99f-7bd353f3f034
Closes: https://github.com/openedx/tutor-contrib-aspects/issues/797
> fix: delay loading of unfocused dashboards

- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
See: https://github.com/openedx/wg-build-test-release/issues/386
> chore: update Django to 4.2.16 for Redwood - Security Patch

- CHANGELOG.rst
- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/signals.py
- platform_plugin_aspects/tests/test_signals.py
> fix: wait for transaction commit before trying to sink models

- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/sinks/base_sink.py
- platform_plugin_aspects/sinks/tests/test_base_sink.py
- platform_plugin_aspects/sinks/tests/test_course_overview_sink.py
When event sinks are enabled in the config or waffle flag, but the model itself doesn't exist we were throwing errors that caused downstream errors. We now warn on this condition and return the model as disabled instead.
Still needs manual testing, leaving in draft for now.
Closes: #96
> fix: Event sink errors when enabled models are missing

- platform_plugin_aspects/__init__.py
- platform_plugin_aspects/extensions/filters.py
- platform_plugin_aspects/extensions/tests/test_filters.py
- platform_plugin_aspects/settings/common.py
- platform_plugin_aspects/settings/production.py
- platform_plugin_aspects/tests/test_utils.py
- platform_plugin_aspects/tests/test_views.py
- platform_plugin_aspects/urls.py
- platform_plugin_aspects/utils.py
- platform_plugin_aspects/views.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
- test_settings.py
Adds an API endpoint for in-context Supserset dashboards.
This uses the dashboards from openedx/tutor-contrib-aspects#1046.
[In-Context Metrics for Studio: Product Requirements](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4694835220/In-Context+Metrics+for+Studio+Product+Requirements)
1. Add this repository checked out to this branch as a Tutor mountpoint: `tutor mounts add platform-plugin-aspects`
2. Install tutor-contrib-aspects from openedx/tutor-contrib-aspects#1046
3. Enable Aspects as instructed in [tutor-contrib-aspects](https://github.com/openedx/tutor-contrib-aspects) (ignoring the pip install tutor-contrib-aspects, as it should be installed from the PR above)
4. Add and enable the following Tutor plugin in order to use the local copy instead of the one installed by …
> feat: API endpoint for in-context Supserset dashboards
